# This is the workflow to make and push wheels to PyPi

name: Build Wheels
on:
  push:
    branches: [ kaizoku ]
    paths-ignore:
      - '.gitignore'
      - '.npmignore'
      - '.pre-commit-config.yaml'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'install_nodejs.sh'
      - 'example/*'
      - '.github/*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: windows-latest
    steps:
      - name: Install Python3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pip requirements
        run: |
          python -m pip install twine
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: tmp/
      - name: Extract artifacts
        run: |
          md dist
          Get-ChildItem -Path .\tmp -Recurse -File | Move-Item -Destination .\dist
      - name: Push to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          echo "${{ github.ref }} ${{ github.workspace }}"
          python -m twine check dist/*
          python -m twine upload dist/*